#ifndef ELGFORWARD_SHADERS_REGISTERS_H_
#define ELGFORWARD_SHADERS_REGISTERS_H_

#ifdef __cplusplus
#define CONSTANT_BUFFER_REGISTER(num) num
#else
#define CONSTANT_BUFFER_REGISTER(num) register(b##num)
#endif // __cplusplus

#define PER_FRAME_CONSTANT_BUFFER_REGISTER CONSTANT_BUFFER_REGISTER(0)
#define PER_CAMERA_CONSTANT_BUFFER_REGISTER CONSTANT_BUFFER_REGISTER(1)
#define PER_OBJECT_CONSTANT_BUFFER_REGISTER CONSTANT_BUFFER_REGISTER(2)
#define PER_MATERIAL_CONSTANT_BUFFER_REGISTER CONSTANT_BUFFER_REGISTER(3)

#ifdef __cplusplus
#define TEXTURE_REGISTER(num) num
#else
#define TEXTURE_REGISTER(num) register(t##num)
#endif // __cplusplus

#define POINT_LIGHT_BUFFER_REGISTER TEXTURE_REGISTER(0)
#define SPOT_LIGHT_BUFFER_REGISTER TEXTURE_REGISTER(1)
#define DIRECTIONAL_LIGHT_BUFFER_REGISTER TEXTURE_REGISTER(2)

#define DIFFUSE_TEXTURE_REGISTER TEXTURE_REGISTER(3)

#ifdef __cplusplus
#define SAMPLER_REGISTER(num) num
#else
#define SAMPLER_REGISTER(num) register(s##num)
#endif // __cplusplus

#define LINEAR_SAMPLER_REGISTER SAMPLER_REGISTER(0)

#endif  // ELGFORWARD_SHADERS_REGISTERS_H_
