#ifndef ELGFORWARD_SHADERS_REGISTERS_H_
#define ELGFORWARD_SHADERS_REGISTERS_H_

#ifdef __cplusplus
#define CONSTANT_BUFFER_REGISTER(num) num
#else
#define CONSTANT_BUFFER_REGISTER(num) register(b##num)
#endif // __cplusplus

#define PER_FRAME_CONSTANT_BUFFER_REGISTER CONSTANT_BUFFER_REGISTER(0)
#define PER_CAMERA_CONSTANT_BUFFER_REGISTER CONSTANT_BUFFER_REGISTER(1)
#define PER_OBJECT_CONSTANT_BUFFER_REGISTER CONSTANT_BUFFER_REGISTER(2)
#define PER_MATERIAL_CONSTANT_BUFFER_REGISTER CONSTANT_BUFFER_REGISTER(3)

#endif  // ELGFORWARD_SHADERS_REGISTERS_H_
